### ISSUE TITLE
Unable to locate the specified class: Session.php

### ISSUE THREAD

**Issue by eyounelson** [bvrignaud/ci-fb-ion-auth#1]
After redirection from Facebook, I get the error:
Unable to locate the specified class: Session.php

It's not formatted like CI error so I wonder if it's from Facebook?

**Comment by bvrignaud** [comment]
Does ion-auth works ?

**Comment by eyounelson** [comment]
Yes, it works.

**Comment by bvrignaud** [comment]
What is your CodeIgniter Version ?

**Comment by eyounelson** [comment]
3.1.8
I posted the issue on CI's slack chat and  someone mentioned that it's an
error from the core/common.php file.

I implemented a workaround before this info (I still prefer your library
though) and am very occupied for the next few days.
I'll try the suggestion from the slack chat over the weekend and will
report my results.

**Comment by eyounelson** [comment]
Hi,
adding `$this->ci->load->library('Session')` to the __contruct function of the library file fixed the issue.

**Comment by bvrignaud** [comment]
Nice.
I add this to the library.
